### PR TITLE
Flyout modal

### PR DESCRIPTION
**Pull request by brettgoulder**

### CODE REVIEW

File: package.json [hunk 1]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "@heroku/react-hk-components",
-  "version": "0.9.0",
+  "version": "0.9.5",
```
Comment (uhoh-itsmaciek) [inline package.json]: Can you revert this? We've been doing version bumps via `np` and I think it makes sense to keep doing that. I'll add a patch to document how we release it.

**Comment by uhoh-itsmaciek** [comment]
@brettgoulder looks like storybook isn't happy:

>ERROR in [at-loader] ./node_modules/@types/react/index.d.ts:26:22 
>    TS2307: Cannot find module 'csstype'.

I think you need to either install the type definitions for this dep or add the module to `src/declarations.d.ts`.

**Comment by uhoh-itsmaciek** [comment]
@brettgoulder does this work for you in Storybook? These open fine for me, but I can't close the modal in any of the four stories. No errors in console.

File: package.json [hunk 2]
```diff
@@ -9,26 +9,29 @@
...
-    "classnames": "2.2.5",
     "d3": "^5.4.0",
     "lodash": "4.17.5",
     "moment": "2.21.0",
+    "classnames": "^2.2.6",
     "prop-types": "15.x",
-    "react": "^16.4.0",
-    "react-dom": "16.x",
+    "react": "16.3.2",
+    "react-dom": "16.3.2",
```
Comment (uhoh-itsmaciek) [inline package.json]: Were you able to figure out why this doesn't work with 16.4? I'm reluctant to downgrade just because this doesn't work...
